Entity de membresia y reserva creados con el usuarioDao
AngelG-JAPY/Proyecto-cine-poo2 pull request #6
Opened 2021-11-15 23:16 UTC by JavierLo24

Mire si ta bien el DAO xd

2021-11-15 23:40 UTC, AngelG-JAPY commented
En el método actualizar falta especificar el id (donde va el where). 

En el método listar tiene que crear una instancia de la clase Membresia y guardar toda la información de la membresia, no solo el id. Métase en mi rama y vea la consulta que yo hice para la función (no la replique toda, pues es muy larga, solo use el join con la tabla membresía ya acomode el resto) .

2021-11-15 23:42 UTC, AngelG-JAPY requested changes
Acomode todo lo que mencione.

2021-11-20 22:00 UTC, JavierLo24 commented
ya....creo

2021-11-20 22:00 UTC, JavierLo24 commented
Igual monté mas archivos xd no recordaba este request :'v

2021-11-21 15:39 UTC, JavierLo24 commented
Ahora el controller de usuario xd

2021-11-23 17:26 UTC, AngelG-JAPY requested changes
Testee y compruebe

2021-11-23 17:28 UTC, closed without merging